### ISSUE TITLE
Cannot Send Two Messages Using Example from "Create an Actor"

### ISSUE THREAD

**Issue by mrwizard82d1** [Horusiath/Akkling#116]
I'm learning both Akka.NET and F# so most likely the problem is me. Here's my code snippet:

When I run the following program snippet which uses `helloref` example from the "Create an Actor" wiki page, I can successfully send **one** message; however, all subsequent messages are processed as "dead letters."

```
open Akkling

[<EntryPoint>]
let main argv =
    use system = System.create "my-system" (Configuration.defaultConfig())
    let helloRef = spawn system "hello-actor" <| props(fun context ->
        let rec loop () = actor {
            let! msg = context.Receive ()
            match msg with
            | "stop" -> return Stop // effect - stops current actor
            | "unhandle" -> return Unhandled // effect - marks message as unhandled
            | x -> 
                printfn "%s" x
                return! loop ()
        }
        loop ())
   
    helloRef <! "Tom"
    helloRef <! "Dick"
    
    system.Terminate().Wait()
    
    0 // return an integer exit code
```

**Comment by Horusiath** [comment]
What your code shows, is that you're creating an actor, sending two messages to it, and without waiting for them to be handled (`<!` is non-blocking operation), you're immediatelly shutting down the entire actor system - which means also killing all actors living inside. 

The fact, that you've managed to successfully get a single message looks like a sheer luck, because system termination takes long enough, that actor could handle at least one message.

If you want to be sure, that your actor handled all messages, don't shutdown your system before that - either block your main thread (popular `Console.ReadLine()`) or use ask pattern (`<?` operator instead `<!`) and await the response.

**Comment by mrwizard82d1** [comment]
Thank you very much for looking over my code. Using `Console.ReadLine()` worked. I'm sorry for bothering y'all with such a simple issue.

I had not examined the call to `Terminate()`. Based on other experiences, I understood that the `Terminate` call waited for all actors to finish. My model was wrong. Thanks for helping me to improve my mental model of how Akkling works.
