### ISSUE TITLE
AskResult cases Ok and Error shadow new Result type from FSharp.Core

### ISSUE THREAD

**Issue by object** [Horusiath/Akkling#67]
The Result type available in FSharp.Core 4.4.1 has cases with identical names, so importing Akkling namespace causes undesirable effect. Unqualified 'Ok' and 'Error' are mapped to AskResult type, and in the best case it causes compiler error. In the worst cases (if actor's Mailbox is untyped) it goes unnoticed by the compiler and the error occurs at runtime, so I had to qualify all occurrences of Result cases.

Suggestion:
- Either require qualified access for AskResult
- Or rename its cases to AskOk and AskError

The first one is probably cleaner.

**Comment by Horusiath** [comment]
I'm going to remove `AskResult<>` from the API. After a while it seems to be a flawed idea. More often people are expecting ask to work as extension of RPC - if callee replies with an object, return it unwrapped. If it replied with a failure, throw an exception preserving the stack trace.

This means that `<?` may throw on failed response rather than returning `Status.Failure`. There are two reasons for that:

1. People are too often forgetting to handle that case directly casting the result to desired type, causing cast exception overriding original source of failure.
2. `Status.Failure` works really bad with F# pattern matching.

**Comment by object** [comment]
I see that it can be problematic with F# pattern matching. For our usage it doesn't matter match if the result is wrapped or not (except for the situation I described in this issue) and because of that removing it won't affect much, we will just need to fix compiler errors.

**Comment by object** [comment]
AskResult is removed in 0.7, no longer an issue.
