### ISSUE TITLE
Replacement for mailbox.Defer()

### ISSUE THREAD

**Issue by object** [Horusiath/Akkling#68]
In Akka F# API Defer method is convenient for referencing a set of disposable objects that will be released in PostStop. Akkling doesn't have Defer but instead enbales PostStop event handler. There are two problems with it:
1. PostStop is a Lifecycle event that makes an actor untyped. It's not practical to sacrifice an actor type just to be able to call some function upon actor termination.
2. Defer can be called multiple times which is convenient if an actor implements FSM that changes resources that needs to be disposed. It's harder to achieve the same using PostStop.

Should Defer be implemented for Akkling actors?

**Comment by quartusdev** [comment]
Akka typed on the JVM does this using a seperate signal handling function. Signals in this case are lifecycle events, Terminated messages etc. This way system messages would not interfer with the message type.
You can see an example here: http://akka.io/blog/2017/05/19/signals

This would be a nice approach for the `actorOf` functions. The signal handler would then either take a value of type `obj` and we add active patterns for the signals or we could create a DU for each signal. Using a DU for the signals would look better from an API perspective, but would mean each received system message must be wrapped, meaning some extra overhead.
The signature of the function could look something like this: `Signal -> Effect<'Message> option` where None means an unhandled effect.

Adding an extra channel for signals to the actor expression is harder. I guess `let! msg = context.Receive()` could be made to bind an Either value of signal or user message though. So you would  pattern match like this for example:
```
match msg with
| Signal s -> ... // match and handle lifecycle message etc. here
| Message m -> ... // match and handle normal message here
```

**Comment by Horusiath** [comment]
@quartusdev I've already presented potential akka-typed API for F# [here](https://gist.github.com/Horusiath/31027b41d7d979cde04e100cb012ee88). Regarding actor computation expression - tbh I'm thinking about dropping it. I know that people are used to it, but to be honest, it's more verbose, harder to maintain and has more hideous bugs (i.e. implicitly dropping tail recursion in some cases).

**Comment by quartusdev** [comment]
@Horusiath 
I agree with dropping the actor computation expression, and it could still be implemented as an extension later, since it should do nothing else than chaining behaviours. 
Have you started actually implementing anything yet or just thought about the potential API?

**Comment by Horusiath** [comment]
@quartusdev @object  I've pushed some of my initial work (not compiling yet) to [this branch](https://github.com/Horusiath/Akkling/tree/serious-changes).

**Comment by quartusdev** [comment]
@Horusiath I like it so far. Especially that with the current implementation we shouldn't need any special casing in FunActor, like there previously was for each of the effects and the integration of async in a "first class" way is great too. I would rename `AsnycVal` to something like `MaybeAsync` though, otherwise it kind of sounds like always being async.
If there is anything to do, let me know. I could continue working on it, if you don't mind not doing it yourself.

**Comment by quartusdev** [comment]
Did some experiments aswell, implementing behaviors as a descriminated union type. I deleted a bunch of code just to get it to compile. See: https://github.com/quartusdev/Akkling/tree/behaviours

The test in [Behaviors.fs](https://github.com/quartusdev/Akkling/blob/behaviours/tests/Akkling.Tests/Behaviors.fs) show what it would look like. The names are mostly taken from the Akka typed implementation in Scala. I haven't put much more thought into them.

**Comment by Horusiath** [comment]
@quartusdev I didn't tried to use discriminated unions, as they have limited extendability. I.e. if we're going to use Akka.Cluster.Sharding, `Passivate` mechanism is a natural candidate for the new behavior. However this won't work with DUs or with akka-typed proposed design.

**Comment by quartusdev** [comment]
@Horusiath But that would also mean you can return `Passivate` from a non sharded actor... Wouldn't it be a better idea for those custom actor's to have their own behavior DU? Especially the persistent actor would be a great fit for that. In its current implementation it differs highly from `FunActor.` I know this would cause some code repetition, but since it will only be internal Akkling code, not visible to the API user, that shouldn't be an issue.

So what I am saying is:
Have completly independent actor implementations, for example: `FunActor`, `PersistentFunActor` and `ShardedFunActor`
Each has their own context implementation. This makes it easy to customize them for their specific use case.
Each has their own behavior DU: `Behavior`, `PersistentBehavior` and `ShardedBehavior`. Each behavior one can be easily created (so above long names aren't an issue) à la `Actor.*` for "normal" `Behavior`.

The only reasons against it, I can currently think of are:
1. Code repetition inside of Akkling, since some Behavior handling will overlap
2. It will not be possible to reuse behavior for an actor from a different actor type, since the behavior type won't match. But I am not really sure whether this is a problem in most cases and there could still be a function which wraps a `Behavior` and turns it into an `PersistentBehavior`, for example.

**Comment by Horusiath** [comment]
Closing this one - mailbox defer is not used for a long time, replacted by signal messages and effects. Regarding passivation, a `Passivate` effect was added to complete this part.
