### ISSUE TITLE
How to take a snapshot of a persistent actor?

### ISSUE THREAD

**Issue by object** [Horusiath/Akkling#69]
In the present Akka.NET F# API a call mailbox.SaveSnapshot can be used to save current state. Akkling API doesn't define snapshot saving function. What should be used to force saving a state of a persistent actor?

**Comment by Horusiath** [comment]
It's always possible, as API for direct communication with snapshot store is exposed. However right now it's probably a bit verbose:

```fsharp
let behavior state (ctx: PersistentContext<_>) msg = 
    let snapshotStore = typed ctx.SnapshotStore
    snapshotStore <! SaveSnapshot(SnapshotMetadata(ctx.Pid, ctx.LastSequenceNr ()), state)
```

I'm working on [exposing persistence API](https://github.com/akkadotnet/akka.net/pull/2917) in akka.net using composition (via `IEventStore` interface) rather than inheritance. It should simplify the API.

**Comment by object** [comment]
Thanks, I will stick to the verbose version for now.
