### ISSUE TITLE
Persisted actors questions

### ISSUE THREAD

**Issue by cotyar** [Horusiath/Akkling#81]
Hi Bartosz,
In Akka (and Akka.net) persisted actors it is possible to attach some logic to the Persist (family) calls to be executed just before writing to into the jounal (lambda as the second method parameter). 
Is it possible to achieve the same in Akkling please?

And additionally, just wondering why neither Akka nor Akka.Net has a standard persistent Sink as say a part of the Persistence.Query? 
Is it just a missing functionality or is there some kind of unobvious reasoning why it's not supported out of the box in neither of the platforms?

**Comment by Horusiath** [comment]
@cotyar I have some ideas for changing the API for actors, but so far:

[Persistent actor example](https://github.com/Horusiath/Akkling/blob/master/examples/persistence.fsx). If you want to invoke some code as callback on persisted event, just add that event in your actor message handler. It will be used for both recovery and after persisting an event - if you want to distinct between handling persisted event and recovering you can use `mailbox.IsRecovering()` method eg.:

```fsharp
match msg with
propsPersist(fun ctx ->
        let rec loop state =
            actor {
                let! msg = ctx.Receive()
                match msg with
                | Event(changed) when ctx.IsRecovering() -> 
                    // triggers only when actor recovers after i.e. restart
                    return! loop (state + changed.Delta)
                | Event(changed) -> 
                    // triggers remaining cases - so when actor has persisted an event
                    return! loop (state + changed.Delta)
                | Command(cmd) ->
                    match cmd with
                    | GetState ->
                        ctx.Sender() <! state
                        return! loop state
                    | Inc -> return Persist (Event { Delta = 1 })
                    | Dec -> return Persist (Event { Delta = -1 })
            }
        loop 0)
```

Regarding Persistence.Query - IMO the reason, why they are not native part of Akka.Persistence was because persistent queries appeared much later, and for compatibility reasons, not all persistence providers have exposed their API for persistence queries on time. However, the most popular implementations already expose them (i.e. all SQL providers share [the same persistence query package](https://www.nuget.org/packages/Akka.Persistence.Query.Sql/)) and you can use them in F# as well.

**Comment by cotyar** [comment]
Bartosz, great thanks for a very detailed answers!

For the _propsPersist_. Assuming I've got a usecase around each Command requiring:
- Checking the validity of the command (ok, this one quite obviously called before the Persist(-Async))
- Assigning each event a monotonic number (id within the sequence), heavily preferrably without gaps
- Encode each event together with the assigned number
- Only after that saving to disk/db.
The options I've tried/can imagine are: 
- Following the example above + snapshots = I failed to sync LastSequenceNo with the corresponding one within the state. Also having troubles with the encoding part as at the event handling stage the data _has been already_ persisted into the journal.
- Adding an EventAdapter - requires a config in HOCON (so not that straight forward to setup from a fsx file) and doesn't have the sequence number available during encoding.
- Assign the seq number/encode in a stage before saving (in another actor or stream stage) - recovery consistency become not clear (as the pre-save-streamlining actor needs to know the last recovered seq number)
- Do some defer magic?

"Regarding Persistence.Query" - it's a good answer but to a slightly different question ;-)
"why neither Akka nor Akka.Net has a standard persistent _Sink_" - Persistence.Query in both (at least as far as I discovered) provides _Source_-s but not _Sink_-s. 
For example doing something similar to what you kindly described above with backpressure and semantics like _Sink.persist pid onCommand onAfterEvent_.

**Comment by Horusiath** [comment]
@cotyar regarding your questions:

Each event is assigned a SequenceNr, which is a monotonically incremented `long` (it doesn't produce any gaps). Those ids are created automatically. You can check the last seqnr using `ctx.LastSequenceNr`. Every user-defined persisted event is wrapped into wrapper which contains info about what serializer has been used to serialize that event, as well as the persistence id of the emitting actor and the sequence nr. unique for that event in scope of a given persistence id (persistenceId + seqNr together build unique identifier of an event).

Regarding persistent sinks - they're not there right now, however there are experiments of building entire [akka eventsourcing module](https://github.com/Horusiath/Akka.Streams.Eventsourcing) using streaming primitives.

Regarding your problems with sequence numbers, can you tell more, since I think I don't quite understand your question.

**Comment by cotyar** [comment]
Bartosz, you answered everything I was looking for.
Dzenkue barzo!

Many thanks indeed man.
