### ISSUE TITLE
How can actorOf2 send an initial message to itself?

### ISSUE THREAD

**Issue by vasily-kirichenko** [Horusiath/Akkling#84]
```fsharp
let a = 
    spawnAnonymous system (props (actorOf2 (fun mb ->
        mb.Self <! 0
        let loop () msg =
            printfn "got %d" msg
            ignored()
        loop())))

a <! 1
```
It cause endless output:
```
got 0
got 0
got 0
got 0
got 0
got 0
...
```

**Comment by vasily-kirichenko** [comment]
I ended up with this
```fsharp
let spawn system arg =
        let a = spawn system "foo" (props arg)
        a <! Message
        a
```
As I understand, the message won't be send to the actor if it's restarted.

**Comment by Horusiath** [comment]
I can think of 2 ways:

#### Use `become` effect

It's a small change over your implementation:

```fsharp
let a = 
    spawnAnonymous system (props (actorOf2 (fun mb ->
        mb.Self <! 0
        let loop () msg =
            printfn "got %d (initial)" msg
            // replaced ignored with become (next behavior)
            become(fun msg -> 
                printfn "got %d (continuous)" msg
                ignored())
        loop())))

a <! 1
```
This returns:

```
got 1 (initial)
got 0 (continuous)
```
as sending message triggers first outer behavior to run, which then sends 0 message to itself.


#### Use actor [lifecycle events](https://github.com/Horusiath/Akkling/wiki/Managing-actor's-lifecycle)

```fsharp
let handler mb msg =
    match msg with
    | LifecycleEvent e ->
        match e with 
        | PreStart -> printfn "initialized"; 
        | _ -> ()
    | :? int as i -> printfn "got %d" i
    ignored()
let a =  spawnAnonymous system <| props (actorOf2 (fun mb msg ->)) |> retype
```
This will trigger "initialized" message, but it also defaults `handler` behavior to accept any `obj` as a message (thanks to lack of union types). Solution for that is to cast output `ActorRef<obj>` to desired type using `retype` function.

**Comment by vasily-kirichenko** [comment]
Thanks. I tried the variant with lifecycle events... The actors' code became as twice as long and complex :( So I went with the `become` option and I've made it a bit nicer:
```fsharp
let a = 
    actorOf2 (
        let loop (mb: Actor<int>) msg =
            printfn "got %d" msg
            mb.Schedule (TimeSpan.FromSeconds 1.0) mb.Self 33 |> ignore
            ignored()
        
        fun mb _ ->
            mb.Self <! 0
            become (loop mb)
    ) 
    |> props |> spawnAnonymous system

a <! 1
```
The only question that's left: is it safe to pass `mb: Actor<_>` from one behavior to another (as it's done in this snippet)?

**Comment by vasily-kirichenko** [comment]
And even simpler!
```fsharp
let a = 
    props (
        let loop (mb: Actor<int>) msg =
            printfn "got %d" msg
            mb.Schedule (TimeSpan.FromSeconds 1.0) mb.Self 33 |> ignore
            ignored()
        
        fun mb ->
            mb.Self <! 0
            become (loop mb)
    ) 
    |> spawnAnonymous system

a <! 1
```
:)
I'm not sure how, but this works without passing the props to `actorOf2`.

**Comment by Swoorup** [comment]
@Horusiath I am bit confused about the  as it why `become` requires a msg parameter when it returns a Effect<'Message> already? 

```fsharp
    let become (effect: Effect<_>) =
        become (fun initialMsg ->
            printfn "MSG: %A" initialMsg
            effect
            )
        
    let behaviour (m: Actor<_>) =
        
        let rec readyLoop () =
            actor {
                let! msg = m.Receive ()
                printfn "Received from readyLoop: %A" msg
                match msg with
                | StartJob args -> return become (searchForJobLoop ())
                | FindRunningJob job -> return Ignore
            }
        and searchForJobLoop () =
            actor {
                let! msg = m.Receive ()
                printfn "Received from searchForJobLoop: %A" msg
                match msg with
                | StartJob args -> return become (readyLoop ())
                | FindRunningJob job -> return Ignore
            }
        
        readyLoop ()

    let clusterSystem = System.create "basic-sys" <| Configuration.defaultConfig()
    let apiMaster = spawn clusterSystem "api" <| props ApiMaster.behaviour

    apiMaster <! ApiMasterCmd.StartJob 1
    apiMaster <! ApiMasterCmd.StartJob 2
    apiMaster <! ApiMasterCmd.StartJob 3
    apiMaster <! ApiMasterCmd.StartJob 4
```

Output: 

```
Received from readyLoop: StartJob 1
MSG: StartJob 2
Received from searchForJobLoop: StartJob 3
MSG: StartJob 4
```

Is it possible to switch the msg loop right after become is invoked? i.e I want to be seeing StartJob 2 from the second loop as well.

**Comment by Horusiath** [comment]
@Swoorup if you want to preinitialize actor inside the handler you may use lifecycle events (see: [wiki](https://github.com/Horusiath/Akkling/wiki/Managing-actor's-lifecycle)). Due to limitation of F# type system, this will require from you to have actor's message type to be an `obj` - however you can always cast `IActorRef<obj>` to `IActorRef<Msg>` by using `retype` function.

**Comment by Swoorup** [comment]
The second snippet is just what I wanted. But wondering what is the purpose of become having the signature `'Msg -> Effect<'Msg>` instead just `Effect<'Msg>`?

also wondering in order to subscribe to lifecycle events could you could instead use a slightly different version of `m.Receive`, maybe `m.ReceiveWithLifeCycle` ? which returns a union like 
`type WithLifeCycleEvent<'a> = LifeCycleEvent of LifeCycleEvent | Msg of 'a`

So you don't need to cast it to `obj`

**Comment by Horusiath** [comment]
@Swoorup `become` is meant to be used, when you don't use `actor` computation expression (example in the README file). In all other cases it's supposed to work with tail recursive function calls. It takes message as a parameter, because it changes the behavior of an actor, which is a function of message->effect (effect itself determines what actor should do after processing the message eg. stop itself or mark message as unhandled).

I also don't see a why do you need a mutable state? Example:

```fsharp
let counter ctx = 
  let rec loop state (ctx: Actor<_>) = actor {
    match! ctx.Receive() with
    | Add delta -> return! loop (state+delta)
    | _ -> return Unhandled
  }
  loop 0 ctx
```

It can be used with data of any complexity.

**Comment by Swoorup** [comment]
@Horusiath Is there a comms channel other than github we can chat? :P 
In here https://github.com/petabridge/akkadotnet-code-samples/blob/master/Cluster.WebCrawler/src/WebCrawler.TrackerService/Actors/ApiMaster.cs the prestart creates another actorref. Do you mean to use a state with an optional actorref and just pass it around? I guess that would work.

Regarding adding extra receive method, I fiddled around a bit but couldn't get it to work. It doesn't like the fact that inner type is transformed to `WithLifeTimeCycleMsg` due to some odd constraint that Actor<'T> must only have Effect<'T> (I admit I am not totally sure whats going on)

```fsharp
type PassThroughEffect<'a>(msg: 'a) =
    interface Effect<'a> with
      member _.WasHandled() = false
      member _.OnApplied(ctx: ExtActor<'a>, msg: 'a) =
        ()
  
  type WithLifeTimeCycleMsg<'a> =
    | Lifecycle of LifecycleEvent
    | UserMsg of 'a

  type Actor<'a> with
    member x.ReceiveAsObj() =
        actor {
          let! msg = IO<obj>.Input
          match msg with
          | LifecycleEvent e -> return PassThroughEffect(Lifecycle e)
          | :? 'a as i -> return PassThroughEffect(UserMsg i)
          | _ -> return Unhandled 
        } 
```
